### ISSUE TITLE
Experiment entry not found in MLFlow

### ISSUE THREAD

**Issue by 1pyroaqua** [aws-samples/amazon-sagemaker-mlflow-fargate#1]
Issue:

Experiment not getting tracked in MLFlow
1. I created the stack by following the instructions provided in the README
2. I spun-up a SageMaker Notebook instance
3. Ran one of the example notebook

Output from SageMaker Notebook:
```console
algo-1-8lk9t_1  | INFO:root:reading data
algo-1-8lk9t_1  | INFO:root:building training and testing datasets
algo-1-8lk9t_1  | INFO: 'boston-house' does not exist. Creating a new experiment
algo-1-8lk9t_1  | INFO:root:training model
algo-1-8lk9t_1  | INFO:root:evaluating model
algo-1-8lk9t_1  | INFO:root:AE-at-10th-percentile: 0.3148059956709947
algo-1-8lk9t_1  | INFO:root:AE-at-50th-percentile: 1.5540873015873053
algo-1-8lk9t_1  | INFO:root:AE-at-90th-percentile: 4.351567142857139
algo-1-8lk9t_1  | INFO:root:saving model in MLflow
algo-1-8lk9t_1  | 2020-12-05 01:46:05,404 sagemaker-training-toolkit INFO     Reporting training SUCCESS

```
Couldn't find the Experiment entry in the MLFlow
<img width="1276" alt="Screen Shot 2020-12-04 at 9 22 37 PM" src="https://user-images.githubusercontent.com/64650227/101234990-51c62f80-3692-11eb-8402-ff47f92e3020.png">

**Comment by SofianHamiti** [comment]
Can you check those 2 things and confirm if it helps: 
- the IAM role of your SageMaker Notebook instance has access to the S3 bucket with the name `s3://mlflow-artifact...`
- in the first cell of the notebook, you set `tracking_uri = '<YOUR MLFLOW SERVER URI>' `. You can find this URI in CloudFormation `Outputs` when your stack finishes to deploy.
- you have refreshed the MLflow page when your training job finishes. the experiement with the run(s) should appear.

**Comment by 1pyroaqua** [comment]
> Can you check those 3 things and confirm if it helps:
> 
> * the IAM role of your SageMaker Notebook instance has access to the S3 bucket with the name `s3://mlflow-artifact...`
> * in the first cell of the notebook, you set `tracking_uri = '<YOUR MLFLOW SERVER URI>' `. You can find this URI in CloudFormation `Outputs` when your stack finishes to deploy.
> * you have refreshed the MLflow page when your training job finishes. the experiement with the run(s) should appear.

It granted permission for the `s3://mlflow-artifact...` S3 bucket and it worked. Thank you!

**Comment by petulla** [comment]
One other fix for this, if anyone else gets stuck, is I needed to add http:// in front of the URI printed in the console when using in Sagemaker with MLflow.
