### ISSUE TITLE
authentication

### ISSUE THREAD

**Issue by chanansh** [aws-samples/amazon-sagemaker-mlflow-fargate#2]
any chance to add https://www.digitalocean.com/community/tutorials/how-to-set-up-password-authentication-with-apache-on-ubuntu-16-04 to the example?

**Comment by SofianHamiti** [comment]
Hi @chanansh, thanks for your feedback.
Authentication is out of scope for this repo and [you can refer to this implementation](https://github.com/aws-samples/aws-mlflow-sagemaker-cdk) for an example.
