### ISSUE TITLE
URLs loading endless

### ISSUE THREAD

**Issue by SaschaHeyer** [aws-samples/amazon-sagemaker-mlflow-fargate#6]
I have successfully deployed the stack
![endless loading](https://user-images.githubusercontent.com/1991664/169767768-500352b1-8ad0-4f00-8472-76131ee02efd.png)

But when trying to open the URI from the load balancer present in the stack outputs, it loads endless and does not open the UI. 
Any suggestions?

**Comment by SofianHamiti** [comment]
Hi @SaschaHeyer, I have just bumped to MLflow 1.26.1.

Can you confirm if it fixes protobuf and loading issue on your side?
